// ---| self |---
import css from './UI.module.scss'

export const Colors = {
  red1: css.red1,
  red2: css.red2,
  red3: css.red3,
  red4: css.red4,
  red5: css.red5,
  red6: css.red6,
  red7: css.red7,
  red8: css.red8,
  red9: css.red9,
  red10: css.red10,
  volcano1: css.volcano1,
  volcano2: css.volcano2,
  volcano3: css.volcano3,
  volcano4: css.volcano4,
  volcano5: css.volcano5,
  volcano6: css.volcano6,
  volcano7: css.volcano7,
  volcano8: css.volcano8,
  volcano9: css.volcano9,
  volcano10: css.volcano10,
  orange1: css.orange1,
  orange2: css.orange2,
  orange3: css.orange3,
  orange4: css.orange4,
  orange5: css.orange5,
  orange6: css.orange6,
  orange7: css.orange7,
  orange8: css.orange8,
  orange9: css.orange9,
  orange10: css.orange10,
  gold1: css.gold1,
  gold2: css.gold2,
  gold3: css.gold3,
  gold4: css.gold4,
  gold5: css.gold5,
  gold6: css.gold6,
  gold7: css.gold7,
  gold8: css.gold8,
  gold9: css.gold9,
  gold10: css.gold10,
  yellow1: css.yellow1,
  yellow2: css.yellow2,
  yellow3: css.yellow3,
  yellow4: css.yellow4,
  yellow5: css.yellow5,
  yellow6: css.yellow6,
  yellow7: css.yellow7,
  yellow8: css.yellow8,
  yellow9: css.yellow9,
  yellow10: css.yellow10,
  lime1: css.lime1,
  lime2: css.lime2,
  lime3: css.lime3,
  lime4: css.lime4,
  lime5: css.lime5,
  lime6: css.lime6,
  lime7: css.lime7,
  lime8: css.lime8,
  lime9: css.lime9,
  lime10: css.lime10,
  green1: css.green1,
  green2: css.green2,
  green3: css.green3,
  green4: css.green4,
  green5: css.green5,
  green6: css.green6,
  green7: css.green7,
  green8: css.green8,
  green9: css.green9,
  green10: css.green10,
  cyan1: css.cyan1,
  cyan2: css.cyan2,
  cyan3: css.cyan3,
  cyan4: css.cyan4,
  cyan5: css.cyan5,
  cyan6: css.cyan6,
  cyan7: css.cyan7,
  cyan8: css.cyan8,
  cyan9: css.cyan9,
  cyan10: css.cyan10,
  blue1: css.blue1,
  blue2: css.blue2,
  blue3: css.blue3,
  blue4: css.blue4,
  blue5: css.blue5,
  blue6: css.blue6,
  blue7: css.blue7,
  blue8: css.blue8,
  blue9: css.blue9,
  blue10: css.blue10,
  geekblue1: css.geekblue1,
  geekblue2: css.geekblue2,
  geekblue3: css.geekblue3,
  geekblue4: css.geekblue4,
  geekblue5: css.geekblue5,
  geekblue6: css.geekblue6,
  geekblue7: css.geekblue7,
  geekblue8: css.geekblue8,
  geekblue9: css.geekblue9,
  geekblue10: css.geekblue10,
  purple1: css.purple1,
  purple2: css.purple2,
  purple3: css.purple3,
  purple4: css.purple4,
  purple5: css.purple5,
  purple6: css.purple6,
  purple7: css.purple7,
  purple8: css.purple8,
  purple9: css.purple9,
  purple10: css.purple10,
  magenta1: css.magenta1,
  magenta2: css.magenta2,
  magenta3: css.magenta3,
  magenta4: css.magenta4,
  magenta5: css.magenta5,
  magenta6: css.magenta6,
  magenta7: css.magenta7,
  magenta8: css.magenta8,
  magenta9: css.magenta9,
  magenta10: css.magenta10,
  gray1: css.gray1,
  gray2: css.gray2,
  gray3: css.gray3,
  gray4: css.gray4,
  gray5: css.gray5,
  gray6: css.gray6,
  gray7: css.gray7,
  gray8: css.gray8,
  gray9: css.gray9,
  gray10: css.gray10,
  gray11: css.gray11,
  gray12: css.gray12,
  gray13: css.gray13,
  black: css.black,
  white: css.white,
  shadow: css.shadow,
}

export const Alpha = {
  xxsAlpha: css.xxsAlpha,
  xsAlpha: css.xsAlpha,
  smAlpha: css.smAlpha,
  mdAlpha: css.mdAlpha,
  lgAlpha: css.lgAlpha,
  xlAlpha: css.xlAlpha,
  xxlAlpha: css.xxlAlpha,
}

export const TextStyleStatus = {
  secondary: css.statusSecondary,
  success: css.statusSuccess,
  warning: css.statusWarning,
  danger: css.statusDanger,
  info: css.statusInfo,
  disabled: css.statusDisabled,
}

export const Base = {
  size: css.baseSize,
  borderSize: css.baseBorderSize,
  units: css.baseUnits,
}

export const ThemeUI = {
  darkBackground: css.themeDarkBackground,
  darkText: css.themeDarkText,
  lightBackground: css.themeLightBackground,
  lightText: css.themeLightText,
}

export const Theme = {
  dark: css.themeDark,
  light: css.themeLight,
}

export type UIThemeTypes = keyof typeof Theme
