version: "3.8"
name: dashboard-server

services:
  mongodb-pod:
    image: mongo:latest
    container_name: mongodb-pod
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volumes:/data/db

volumes:
  mongodb_volumes:
